### ISSUE TITLE
다른 페이지로 넘어가면 HTTP로 변경되는 현상

### ISSUE THREAD

**Issue by Hoto-Cocoa** [rexpress/rexpress.github.io#1]
![image](https://cloud.githubusercontent.com/assets/21969938/22995041/871e8cd0-f40c-11e6-9100-cfe41ca8c5e9.png)
![image](https://cloud.githubusercontent.com/assets/21969938/22995051/917b4fe2-f40c-11e6-8b09-df7b4d968315.png)
분명 링크는 HTTPS로 들어가지는데 (`<a href="/download">Download</a>`) 페이지가 이동 된 후에는 HTTP로 변해버립니다.

**Comment by Hoto-Cocoa** [comment]
상단바는 정상 작동하고, 푸터의 Terms & Service에서도 같은 증상이 일어납니다.

**Comment by Hoto-Cocoa** [comment]
상단바를 제외한 모든 내부링크에서 발생하고 있습니다.

**Comment by Prev** [comment]
해결되었습니다
